### PR TITLE
3D logo on the landing page is a bit awkward

### PR DESCRIPTION
**Pull request by klanmiko**

### CODE REVIEW

**Comment by lovincyrus** [comment]
Preview: https://5be37a363813f0735a6f2b1c--hackdavis.netlify.com/

There should only be one hackdavis logo on the landing page. It's redundant to have two. @klanmiko

**Comment by lovincyrus** [comment]
This looks good to me. The landing illustration should be reverted/replaced asap.

2 hackdavis logo on landing seems redundant to me. The one on the building should prob be removed.

cc: @klanmiko

**Comment by klanmiko** [comment]
@lovincyrus which looks better? the current preview or something like this: assuming the logo on top of the tower gets removed (still waiting on asset)
screenshot_2018-11-07 hackdavis 2019 february 9 - 10 2019 1

**Comment by lovincyrus** [comment]
Assuming the logo on top of the tower gets removed, the current preview looks better. The attachment view would look nice only if there wasn't any illustration and was the only thing centered on the landing page.

Solutions:
1. current preview hackdavis logo
2. remove logo on top of the tower

👍

**Pull request merged**
